Adding prepare shooter
ligerbots/Crescendo2024 pull request #38
Opened 2024-02-13 00:19 UTC by evan-gan

2024-02-13 14:45 UTC, prensing requested changes

2024-02-15 00:55 UTC, evan-gan commented
Should have addressed all of your comments, @prensing

2024-02-15 02:10 UTC, prensing requested changes

2024-02-15 02:10 UTC, prensing commented on src/main/java/frc/robot/FieldConstants.java
> +    public static final Translation2d SPEAKER = new Translation2d(0, 5.5461679526); //Pose should be correct
Really. I think that goes to nanometers!!! What is the smallest distance we care about on the field?

Please trim to 2 decimal places.

2024-02-15 02:10 UTC, prensing commented on src/main/java/frc/robot/commands/PrepareShooter.java
> +        m_robotPose = () -> driveTrain.getPose();
This still will not work. I will post in Slack.

2024-02-16 15:35 UTC, prensing approved these changes

2024-02-16 15:38 UTC, merged