Wait for correct shooter speed
ligerbots/Crescendo2024 pull request #7
Opened 2024-01-26 01:26 UTC by SuperYoshi10000

Make sure the feeders are spinning fast enough before shooting

2024-01-26 14:33 UTC, prensing requested changes

2024-01-26 14:33 UTC, prensing commented on src/main/java/frc/robot/commands/WaitForCorrectShooterSpeed.java
> +  private static final double TOLERANCE = 5; // TODO Tune this later
This is really low. Yes, we will tune it later, but we should start with a reasonable value. RPMs range up to 3000-5000, so what is a more sensible value?

2024-01-26 14:33 UTC, prensing commented on src/main/java/frc/robot/commands/WaitForCorrectShooterSpeed.java
> +public class WaitForCorrectShooterSpeed extends Command {
The command name is poor. It also sets the value.

2024-01-27 00:51 UTC, coachFitz0807 approved these changes

2024-01-27 01:11 UTC, coachFitz0807 approved these changes

2024-01-27 03:20 UTC, prensing requested changes
Mitchell you need to remove the autos. Those should not be in the PR. A PR should stick to closely related changes.

2024-01-30 00:01 UTC, prensing approved these changes

2024-01-30 00:01 UTC, merged