adding bind buttons to farm controllers for climbing
ligerbots/Crescendo2024 pull request #8
Opened 2024-01-26 01:27 UTC by MariaKore

2024-01-26 14:40 UTC, prensing requested changes

2024-01-26 14:40 UTC, prensing commented on src/main/java/frc/robot/Constants.java
> +    public static final double ONSTAGE_LOWER_ELEVATOR = Units.inchesToMeters(10.0); //TODO: TUNE THIS LATER
These constants should be in the Elevator class.

2024-01-27 01:28 UTC, coachFitz0807 reviewed
OVerall, should we also have a TestSetElevatorLength that reads the SmatDashboard and sets the elevator to that length?
And in Elevator.java, REACHER_OFFSET_TOLERANCE_METERS should be OFFSET_TOLERANCE_METERS

2024-01-27 02:16 UTC, MariaKore commented
Hello, I have fixed my mistakes. Now some constants are in the Elevator class and in Elevator.java REACHER_OFFSET_TOLERANCE_METERS is now OFFSET_TOLERANCE_METERS. I am not sure what is SmatDashboard you mean SmartDashboard that displays the bot's data in real time and allow you to control bot variables? Is the TestSetElevatorLength is supposed to be a class or a file? We have SetElevatorLength which is a file in the commands folder.

2024-01-28 02:30 UTC, MariaKore commented
Hello, I have fixed my mistakes. Now some constants are in the Elevator
class and in Elevator.java REACHER_OFFSET_TOLERANCE_METERS is now
OFFSET_TOLERANCE_METERS. I am not sure what is SmatDashboard you mean
SmartDashboard that displays the bot's data in real time and allow you to
control bot variables? Is the TestSetElevatorLength supposed to be a class
or a file? We have SetElevatorLength which is a file in the commands folder.

On Fri, Jan 26, 2024 at 8:28 PM coachFitz0807 ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> OVerall, should we also have a TestSetElevatorLength that reads the
> SmatDashboard and sets the elevator to that length?
> And in Elevator.java, REACHER_OFFSET_TOLERANCE_METERS should be
> OFFSET_TOLERANCE_METERS
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ligerbots/Crescendo2024/pull/8#pullrequestreview-1846776180>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEMAA36I4MKT7KKS6J7UWVDYQRJ3TAVCNFSM6AAAAABCLN6HYCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBWG43TMMJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-28 19:05 UTC, coachFitz0807 reviewed
Don't worry about using the SmartDashboard in the TestSetElevatorCommand. That is being done int he addElevatorTest branch.
For the fixes tothe constants, did you commit those changes and push them? I am not seeeing them.

2024-01-28 20:13 UTC, MariaKore commented
Oh I didn't commit them I'll do it as soon as possible.

On Sun, Jan 28, 2024, 2:05 PM coachFitz0807 ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Don't worry about using the SmartDashboard in the TestSetElevatorCommand.
> That is being done int he addElevatorTest branch.
> For the fixes tothe constants, did you commit those changes and push them?
> I am not seeeing them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ligerbots/Crescendo2024/pull/8#pullrequestreview-1847614700>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEMAA34QCBMDQMGSD6VJTFTYQ2OOXAVCNFSM6AAAAABCLN6HYCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBXGYYTINZQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-31 00:28 UTC, coachFitz0807 reviewed
After you commit, you also have to push so it goes up to Github and the rest of the team can see it. I'm not seeing your changes.

2024-02-02 19:31 UTC, prensing approved these changes

2024-02-02 19:31 UTC, merged